apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
type: kubernetes.io/basic-auth
data:
  username: 4oCYY2FkbWlu4oCZ
  password: 4oCYUEBzc3cwcmTigJk=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app-container
        #image: yasser744/devops-demo-app:72
        image: http://192.168.96.132:8081/docker_jfrog_repo/yasser744/devops-demo-app:72
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: registry-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-svc
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 32000
  selector:
    app: flask-app

